services:
  ros2-dev:
    image: local/ros2-dev:humble
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2-dev-container
    volumes:
      - ../ros2_ws:/root/ros2_ws      # 
      - ../core_algorithms:/root/core_algorithms
      - ../motion_models:/root/motion_models
      - ../data:/root/data
    environment:
      - PYTHONPATH=/root/core_algorithms:/root/motion_models
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - BAG_DIR=${BAG_DIR}
      - TZ=${TZ}
    working_dir: /root/ros2_ws
    platform: linux/arm64
    tty: true
    command:
      - /bin/bash
      - -lc
      - |
        # put into container's ~/.bashrc，and run shell
        grep -qxF 'source /opt/ros/humble/setup.bash' ~/.bashrc || echo 'source /opt/ros/humble/setup.bash' >> ~/.bashrc
        grep -qxF '[ -f ~/ros2_ws/install/setup.bash ] && source ~/ros2_ws/install/setup.bash' ~/.bashrc || echo '[ -f ~/ros2_ws/install/setup.bash ] && source ~/ros2_ws/install/setup.bash' >> ~/.bashrc
        exec bash

