# configs/run_ekf.yaml

sources:
  - type: csv
    params:
      path: ../data/sample_inputs/dummy_imu.csv
      ts_col: timestamp_sec
      topic: imu
      rename:
        gyro_z_radps: wz
  - type: csv
    params:
      path: ../data/sample_inputs/dummy_gnss.csv
      ts_col: timestamp_sec
      topic: gnss
      rename:
        gnss_lat_deg: lat
        gnss_lon_deg: lon
  - type: csv
    params:
      path: ../data/sample_inputs/dummy_mag.csv
      ts_col: timestamp_sec
      topic: mag
      rename:
        mag_x_uT: mx
        mag_y_uT: my

node:
  type: plugins.algos.ekf_node.EKFNode
  params:
    # if no velocity from wheel, EKF will use difference of GNSS position to find approximate v
    R_gnss: [1.0, 1.0]
    R_mag:  0.05
    dt_min: 0.001
    dt_max: 0.2
    use_mag: true
    declination_deg: 0.0

sink:
  type: plugins.csv_sink.CsvSink
  params: { path: ../data/sample_outputs/state_ekf.csv }

options: { realtime: false }
